### ISSUE TITLE
Publish latest version of the extension to Maven (or a SNAPSHOT to Sonatype)

### ISSUE THREAD

**Issue by carlosedp** [quarkiverse/quarkus-scala3#26]
I'd like to as if it's possible to publish the latest code of the extension to Maven and/or snapshots of it.

I've started a Scala 3 sample project and have the extension published would make things easier than installing it locally.

**Comment by gsmet** [comment]
I completely forgot to release the extension when I fixed it, sorry. Let me have a look.

I think I have seen you mentioning a quickstart. I recommend we include it in this repository, similar to what I did there:  https://github.com/quarkiverse/quarkus-smallrye-opentracing .

**Comment by gsmet** [comment]
1.0.0 is available, closing.
